# Generated by Django 5.2.2 on 2026-06-05 06:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(help_text='Original NPZ filename', max_length=255)),
                ('tier', models.CharField(choices=[('TOP', 'Top Performing'), ('BOTTOM', 'Bottom Performing')], max_length=10)),
                ('npz_file', models.FileField(help_text='Path to the NPZ file', upload_to='npz_files/performance/')),
                ('actual_ctr', models.FloatField(blank=True, help_text='Actual CTR (to be updated from admin)', null=True)),
                ('brain_predicted_ctr', models.FloatField(blank=True, help_text='XGBoost regressor predicted CTR (percentage).', null=True)),
                ('brain_predicted_class', models.CharField(blank=True, help_text='Classifier output: "High" or "Low".', max_length=10, null=True)),
                ('brain_predicted_confidence', models.FloatField(blank=True, help_text='Classifier confidence for the predicted class (0–100%).', null=True)),
                ('brain_prediction_tier', models.CharField(blank=True, help_text='Tier label: Strong High / Likely High / Borderline / Likely Low / Strong Low.', max_length=20, null=True)),
                ('brain_ctr_lower_bound', models.FloatField(blank=True, help_text='P10 quantile lower bound for predicted CTR.', null=True)),
                ('brain_ctr_upper_bound', models.FloatField(blank=True, help_text='P90 quantile upper bound for predicted CTR.', null=True)),
                ('brain_model_features', models.JSONField(blank=True, help_text='The 6 extracted brain features used as XGBoost input.', null=True)),
                ('brain_timeseries', models.JSONField(blank=True, help_text='Per-second timeseries data keyed by region.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Performance Video',
                'verbose_name_plural': 'Performance Videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
