# Generated by Django 5.2.2 on 2026-06-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancevideo',
            name='impressions',
            field=models.BigIntegerField(blank=True, help_text='Number of impressions', null=True),
        ),
        migrations.AlterField(
            model_name='performancevideo',
            name='tier',
            field=models.CharField(choices=[('TOP', 'Top Performing'), ('BOTTOM', 'Bottom Performing'), ('COMPETITOR_SUCCESS', 'Competitor Success')], max_length=20),
        ),
    ]
