# Generated by Django 5.2.2 on 2026-06-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_analyzer', '0002_performancevideo_impressions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancevideo',
            name='npz_file',
            field=models.FileField(help_text='Path to the NPZ file', max_length=255, upload_to='npz_files/performance/'),
        ),
    ]
