# Generated by Django 5.2.2 on 2026-06-17 03:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoComparison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video1_file', models.FileField(upload_to='comparisons/')),
                ('video1_name', models.CharField(max_length=255)),
                ('video2_file', models.FileField(upload_to='comparisons/')),
                ('video2_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('winner', models.CharField(blank=True, choices=[('video1', 'Video 1'), ('video2', 'Video 2'), ('tie', 'Tie')], max_length=20, null=True)),
                ('raw_analysis', models.JSONField(blank=True, help_text='Structured JSON from Gemma 4', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Video Comparison',
                'verbose_name_plural': 'Video Comparisons',
                'ordering': ['-created_at'],
            },
        ),
    ]
