# Generated by Django 5.2.2 on 2026-06-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_comparator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocomparison',
            name='video1_file',
            field=models.FileField(max_length=500, upload_to='comparisons/'),
        ),
        migrations.AlterField(
            model_name='videocomparison',
            name='video1_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='videocomparison',
            name='video2_file',
            field=models.FileField(max_length=500, upload_to='comparisons/'),
        ),
        migrations.AlterField(
            model_name='videocomparison',
            name='video2_name',
            field=models.CharField(max_length=500),
        ),
    ]
