# Generated by Django 6.0.6 on 2026-06-18 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural_ranker', '0004_rankingsession_pipeline_type'),
        ('video_comparator', '0002_alter_videocomparison_video1_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocomparison',
            name='ranking_session',
            field=models.OneToOneField(blank=True, help_text='Linked ranking session for intermediate results', null=True, on_delete=django.db.models.deletion.SET_NULL, to='neural_ranker.rankingsession'),
        ),
    ]
