# Generated by Django 5.2.2 on 2026-06-12 07:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RankingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', help_text="Optional label for this ranking session (e.g. 'June Campaign Test').", max_length=255)),
                ('preset', models.CharField(choices=[('default', 'Default (Balanced)'), ('game_ads', 'Game Ads (Visual + Attention)'), ('narrative_ads', 'Narrative Ads (Story + Memory)'), ('music_video', 'Music Video (Audio + Emotion)'), ('brand_awareness', 'Brand Awareness (Memory + Emotion)')], default='default', help_text='Weight preset profile used for ranking.', max_length=30)),
                ('normalization', models.CharField(choices=[('minmax', 'Min-Max (0–1)'), ('zscore', 'Z-Score (Sigmoid)'), ('percentile', 'Percentile Rank')], default='minmax', help_text='Cross-video normalization method.', max_length=20)),
                ('custom_weights', models.JSONField(blank=True, help_text='User-defined dimension weight overrides (JSON dict). Overrides preset if provided.', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('result_summary', models.JSONField(blank=True, help_text='Overall ranking stats: per-dimension min/max/mean, best-per-dimension.', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details when status == FAILED.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ranking Session',
                'verbose_name_plural': 'Ranking Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RankedVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(help_text='Original NPZ filename (without extension).', max_length=255)),
                ('npz_file', models.FileField(help_text='Uploaded TRIBEv2 .npz prediction file.', upload_to='npz_files/rankings/')),
                ('rank', models.IntegerField(blank=True, db_index=True, help_text='1-indexed rank within the session (1 = best).', null=True)),
                ('overall_score', models.FloatField(blank=True, help_text='Overall weighted score (0–100).', null=True)),
                ('dimension_scores', models.JSONField(blank=True, help_text='8 dimension scores (0–100), keyed by dimension name.', null=True)),
                ('strengths', models.JSONField(blank=True, help_text='List of dimension strength labels for this video.', null=True)),
                ('weaknesses', models.JSONField(blank=True, help_text='List of dimension weakness labels for this video.', null=True)),
                ('raw_features', models.JSONField(blank=True, help_text='All 75 extracted brain features (flat dict).', null=True)),
                ('engagement_curve', models.JSONField(blank=True, help_text='Per-second timeseries data for visualization (keyed by region/network).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(help_text='The ranking session this video belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='neural_ranker.rankingsession')),
            ],
            options={
                'verbose_name': 'Ranked Video',
                'verbose_name_plural': 'Ranked Videos',
                'ordering': ['rank'],
            },
        ),
    ]
