# Generated by Django 6.0.6 on 2026-06-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural_ranker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingsession',
            name='preset',
            field=models.CharField(choices=[('default', 'Default (Balanced)'), ('game_ads', 'Game Ads (Visual + Attention)'), ('narrative_ads', 'Narrative Ads (Story + Memory)'), ('music_video', 'Music Video (Audio + Emotion)'), ('brand_awareness', 'Brand Awareness (Memory + Emotion)'), ('custom', 'Custom Weighting')], default='default', help_text='Weight preset profile used for ranking.', max_length=30),
        ),
    ]
