# Generated by Django 5.2.2 on 2026-06-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural_ranker', '0002_alter_rankingsession_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankedvideo',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error details when inference_status == FAILED.', null=True),
        ),
        migrations.AddField(
            model_name='rankedvideo',
            name='inference_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', help_text='Status of the background RunPod inference pipeline.', max_length=20),
        ),
        migrations.AddField(
            model_name='rankedvideo',
            name='video_file',
            field=models.FileField(blank=True, help_text='Uploaded video file for background processing.', null=True, upload_to='videos/rankings/'),
        ),
        migrations.AlterField(
            model_name='rankedvideo',
            name='npz_file',
            field=models.FileField(blank=True, help_text='Uploaded or generated TRIBEv2 .npz prediction file.', null=True, upload_to='npz_files/rankings/'),
        ),
    ]
