# Generated by Django 6.0.6 on 2026-06-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural_ranker', '0003_rankedvideo_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingsession',
            name='pipeline_type',
            field=models.CharField(choices=[('video_comparison', 'Video Comparison'), ('neural_ranking', 'Neural Ranking')], db_index=True, default='neural_ranking', help_text='The type of pipeline this session belongs to.', max_length=20),
        ),
    ]
