# Generated by Django 5.2.2 on 2026-06-04 08:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('original_name', models.CharField(max_length=255)),
                ('mode', models.CharField(default='combination', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('creative_score', models.FloatField(blank=True, null=True)),
                ('hook_rating', models.IntegerField(blank=True, null=True)),
                ('hook_type', models.CharField(blank=True, max_length=150, null=True)),
                ('ad_format_type', models.CharField(blank=True, max_length=150, null=True)),
                ('has_story_narrative', models.BooleanField(blank=True, null=True)),
                ('raw_analysis', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
