# Generated by Django 6.0.6 on 2026-06-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoanalysis',
            options={'ordering': ['-created_at'], 'verbose_name': 'Video Analysis', 'verbose_name_plural': 'Video Analyses'},
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='celery_task_id',
            field=models.CharField(blank=True, db_index=True, help_text='Celery AsyncResult task ID for this analysis job.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='videoanalysis',
            name='mode',
            field=models.CharField(choices=[('combination', 'Combination (Flash + Gemma 31B)'), ('gemini_only', 'Gemini Flash Only'), ('31b_only_no_audio', 'Gemma 31B Visual Only')], default='combination', max_length=50),
        ),
    ]
