# Generated by Django 5.2.2 on 2026-06-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_alter_videoanalysis_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoanalysis',
            name='brain_analysis_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, help_text='Independent status for the brain analysis pipeline.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='brain_celery_task_id',
            field=models.CharField(blank=True, db_index=True, help_text='Celery AsyncResult task ID for the brain analysis job.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='brain_ctr_lower_bound',
            field=models.FloatField(blank=True, help_text='P10 quantile lower bound for predicted CTR.', null=True),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='brain_ctr_upper_bound',
            field=models.FloatField(blank=True, help_text='P90 quantile upper bound for predicted CTR.', null=True),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='brain_error_message',
            field=models.TextField(blank=True, help_text='Error details when brain_analysis_status == FAILED.', null=True),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='brain_model_features',
            field=models.JSONField(blank=True, help_text='The 6 extracted brain features used as XGBoost input.', null=True),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='brain_predicted_class',
            field=models.CharField(blank=True, help_text='Classifier output: "High" or "Low".', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='brain_predicted_confidence',
            field=models.FloatField(blank=True, help_text='Classifier confidence for the predicted class (0–100%).', null=True),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='brain_predicted_ctr',
            field=models.FloatField(blank=True, help_text='XGBoost regressor predicted CTR (percentage).', null=True),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='brain_prediction_tier',
            field=models.CharField(blank=True, help_text='Tier label: Strong High / Likely High / Borderline / Likely Low / Strong Low.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='brain_timeseries',
            field=models.JSONField(blank=True, help_text='Per-second timeseries data keyed by region: emotional, orbital, visual, insula_short, global.', null=True),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='npz_file',
            field=models.FileField(blank=True, help_text='TRIBEv2 .npz prediction file for brain feature extraction.', null=True, upload_to='npz_files/'),
        ),
    ]
